### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by xyllq999** [echonet/lvh#5]
File "run_plax_hypertrophy_inference.py", line 376, in <dictcomp>
    args.update({k.replace('-', '_'): v for k, (v, h) in vars(parser.parse_args()).items()})

**Comment by xyllq999** [comment]
Also, after correct these error in code, I get a new error. RuntimeError: CUDA out of memory. Tried to allocate 3.66 GiB (GPU 0; 11.75 GiB total capacity; 9.65 GiB already allocated; 337.06 MiB free; 9.67 GiB reserved in total by PyTorch). My GPI is 3060, I wonder what GPU are required in this project?

**Comment by YANWANG9678** [comment]
> Also, after correct these error in code, I get a new error. RuntimeError: CUDA out of memory. Tried to allocate 3.66 GiB (GPU 0; 11.75 GiB total capacity; 9.65 GiB already allocated; 337.06 MiB free; 9.67 GiB reserved in total by PyTorch). My GPI is 3060, I wonder what GPU are required in this project?

Hi where did you get the weight file of this model？I could not find any related file of model‘s weight.

**Comment by douyang** [comment]
Need to clear cache of GPU prior to running. Model weights on GitHub as a release.

**Comment by YANWANG9678** [comment]
> 

Hi Dr.douyang, thank you for you reply.
 I found a deeplabv3_resnet50.pt in dynamic.  I know that lvh also use deeplabv3_resnet50 model. Do you mean hypertrophy_model.pt in run_plax_hypertrophy_inference.py is that .pt file?

>

**Comment by YANWANG9678** [comment]
> Need to clear cache of GPU prior to running. Model weights on GitHub as a release.

Thank you! i found it!

**Comment by pranayj77** [comment]
> File "run_plax_hypertrophy_inference.py", line 376, in
> args.update({k.replace('-', '_'): v for k, (v, h) in vars(parser.parse_args()).items()})

What did you change the line to? @xyllq999

**Comment by adildahlan** [comment]
> > File "run_plax_hypertrophy_inference.py", line 376, in
> > args.update({k.replace('-', '_'): v for k, (v, h) in vars(parser.parse_args()).items()})
> 
> What did you change the line to? @xyllq999

It works for me with these two changes:
    `args.update({k.replace('-', '_'): v for k, v in vars(parser.parse_args()).items()})`
    `get_args = lambda l: {k: args[k] for k in l}`
I hope this helps!

**Comment by bwsperry** [comment]
> 

Thanks, this helped me.
But now it is giving me this error. Thoughts?

TypeError: <lambda>() takes 1 positional argument but 2 were given
